project_name: goaldfuse
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
builds:
 - env:
     - CGO_ENABLED=0
   goos:
     - linux
     - darwin
   goarch:
     - amd64
     - arm64
   goarm:
     - 7
   ignore:
     - goos: darwin
       goarch: 386
 - env:
     - CGO_ENABLED=1
     - CC=x86_64-w64-mingw32-gcc
     - CPATH=/home/runner/work/goaldfuse/winfsp-1.10/inc/fuse/
     - CFLAGS="-I /home/runner/work/goaldfuse/winfsp-1.10/inc/fuse/"
   goos:
     - windows
   goarch:
     - amd64

archives:
  - name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64-bit
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
universal_binaries:
  - replace: true