project_name: goaldfuse
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
builds:
 - env:
     - CGO_ENABLED=1
   goos:
     - linux
     - darwin
     - windows
   goarch:
     - amd64
     - 386
     - arm
     - arm64
   goarm:
     - 5
     - 6
     - 7
   ignore:
     - goos: darwin
       goarch: 386

archives:
  - name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64-bit
      386: 32-bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
universal_binaries:
  - replace: true