name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check
      run: pwd
    - run: ls -al
    - run: hostname
    - run: sudo apt update -y 
    - run: sudo apt upgrade -y
      

