name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check
      run: pwd
    - run: ls -al
    - run: hostname
    - run: sudo apt install wget -y
    - run: wget https://github.com/billziss-gh/winfsp/archive/refs/tags/v1.10.tar.gz
    - run: tar xzvf v1.10.tar.gz
    - run: ls -al
      

